name : xnview

uuid : 977158e1-8b83-4a46-aa77-3e3a3e924316

description : "XnViewMP is the enhanced version to XnView."
authors : [XnSoft]
config_version : 0
version : 0.72.0

commands:
- export PATH=$BD_SOFTS/xnview/!VERSION!:$PATH
